Add msg support
dtm-labs/dtmcli-csharp pull request #15
Opened 2022-01-24 11:22 UTC by catcherwong

2022-01-24 11:35 UTC, yedf2 commented
这个pr我要过两天review，有一部分接口做了改动，正在测试中

2022-01-24 11:38 UTC, catcherwong commented
好的

2022-01-25 08:42 UTC, yedf2 requested changes

2022-01-25 08:42 UTC, yedf2 commented on src/Dtmcli/Barrier/BranchBarrier.cs
> +                    return Constant.Succeess;
新的写法与旧的写法不同，不一致。这里返回的话，isOK为false，那么finally会走rollback，实际上原代码和go语言的，都是走的commit。
我还有疑问，旧版本这个地方如果有错误走了异常，没有返回值，貌似会更加清晰。我不太清楚改成了异步之后，错误依旧走异常是否是OK的，如果OK的话，那么是不是优先选择异常？只有QueryPrepared这种，才将异常转为一个确定的是否成功？

2022-01-25 08:42 UTC, yedf2 commented on src/Dtmcli/Msg/Msg.cs
> +                flag = resp.IsSuccessStatusCode;
当这里进行查询之后，如果发现busiCall里面的逻辑已经提交了，那么后续直接submit这个消息会缩短整个事务的时间，会更优
另外这个的返回值，保持跟跟busiCall的返回值一样，可能会更容易理解。一个string，一个bool更容易引起误会

2022-01-25 09:43 UTC, catcherwong commented on src/Dtmcli/Barrier/BranchBarrier.cs
> +                    return Constant.Succeess;
> 新的写法与旧的写法不同，不一致。这里返回的话，isOK为false，那么finally会走rollback，实际上原代码和go语言的，都是走的commit。

这个应该走commit的才对。

2022-01-25 09:56 UTC, catcherwong commented on src/Dtmcli/Barrier/BranchBarrier.cs
> +                    return Constant.Succeess;
> 我还有疑问，旧版本这个地方如果有错误走了异常，没有返回值，貌似会更加清晰。

这里考虑加个返回值是想区分不同类型的错误，现在看来意义不大，旧版本没有返回值从逻辑上是会比较清晰，考虑catch那里rollback之后 throw 出去，让上层来处理会好一点。

> 我不太清楚改成了异步之后，错误依旧走异常是否是OK的，如果OK的话，那么是不是优先选择异常？只有QueryPrepared这种，才将异常转为一个确定的是否成功？

异常这个是OK的，这个要看一下怎么调整比较合适。

2022-01-25 09:56 UTC, catcherwong commented on src/Dtmcli/Msg/Msg.cs
> +                flag = resp.IsSuccessStatusCode;
了解

2022-01-25 12:04 UTC, catcherwong commented on src/Dtmcli/Barrier/BranchBarrier.cs
> +                    return Constant.Succeess;
这里最后决定不采用返回值，用异常来代替。

2022-01-25 12:37 UTC, yedf2 approved these changes

2022-01-25 12:37 UTC, merged